### ISSUE TITLE
license must be GPLv3

### ISSUE THREAD

**Issue by fommil** [brocode/play-routes-mode#10]
emacs is GPLv3 so all `.el` files must be GPLv3. You can't have Apache 2.0.

**Comment by mriehl** [comment]
@fommil is the elisp file format itself GPLv3? I'm also for switching if it's more homogenous that way (and it's easy because the contributor graph is small) but I don't understand why the "interpreter" (gnu emacs in this case) requires the source code to have a certain license?

Is the technical argument that you are not allowed to load code into emacs that is not GPLv3 licensed, so it is technically ok to have this apache but nobody would be able to use it?

Or is the elisp language itself considered to be the same thing as emacs legally so when I write elisp code I'm creating a derivative work?

I've been thinking in "C code license and GCC license are orthogonal to each other so it must be the same thing for elisp" so far but your comment reads like that's wrong.

Anyway, :+1: for changing.

@lunaryorn @syohex @purcell you have contributed code to this project, do you object to relicensing it under the terms of the GPLv3?

**Comment by bomgar** [comment]
https://www.gnu.org/licenses/gpl-faq.en.html

If I understand this correctly we don't have a choice anyway.

**Comment by mriehl** [comment]
I actually read it as the opposite, but I'm not sure which of the many "FAQ" entries you refer to @bomgar 

> Can I use GPL-covered editors such as GNU Emacs to develop nonfree programs? Can I use GPL-covered tools such as GCC to compile them? (#CanIUseGPLToolsForNF)

>    Yes, because the copyright on the editors and tools does not cover the code you write. Using them does not place any restrictions, legally, on the license you use for your code.

**Comment by bomgar** [comment]
If the main program and the plugins are a single combined program then this
means you must license the plug-in under the GPL or a GPL-compatible free
software license and distribute it with source code in a GPL-compliant way.
A main program that is separate from its plug-ins makes no requirements for
the plug-ins.

It depends on how the main program invokes its plug-ins. If the main
program uses fork and exec to invoke plug-ins, and they establish intimate
communication by sharing complex data structures, or shipping complex data
structures back and forth, that can make them one single combined program.
A main program that uses simple fork and exec to invoke plug-ins and does
not establish intimate communication between them results in the plug-ins
being a separate program.

**Comment by mriehl** [comment]
Ok, that sounds like it's

> Is the technical argument that you are not allowed to load code into emacs that is not GPLv3 licensed, so it is technically ok to have this apache but nobody would be able to use it?

then. There is still the case that "being in the language used for plugins" does not imply "being a plugin" IMHO so I guess elisp code does not necessarily need to be GPLed but it would be illegal to load it into emacs (which we want to do)

**Comment by purcell** [comment]
I'm fine with GPLv3 for my contributions, but I also don't agree that all Emacs packages have to be licenced under GPL.

**Comment by fommil** [comment]
@mriehl yes that's a correct interpretation. Hence any non-gpl compatible code can't be legally used in an emacs-lisp program (e.g. clojure derived code) unless relicensed by the author.

**Comment by swsnr** [comment]
I'm fine with GPL 3, too, but I also don't think it's necessary.
